export default [
  {
    id: 'asx',
    city: 'Sydney',
    country: 'Australia',
    flag: 'au',
    name: 'Australia Stock Exchange',
    timeZone: 'Australia/Sydney',
    openTime: {
      hours: 10,
      minutes: 0,
    },
    closeTime: {
      hours: 16,
      minutes: 0,
    },
  },
  {
    id: 'krx',
    city: 'Seoul',
    country: 'South Korea',
    flag: 'kr',
    timeZone: 'Asia/Seoul',
    openTime: {
      hours: 9,
      minutes: 0,
    },
    closeTime: {
      hours: 15,
      minutes: 30,
    },
  },
  {
    id: 'jpx',
    city: 'Tokyo',
    country: 'Japan',
    flag: 'jp',
    name: 'Japan Exchange Group',
    timeZone: 'Asia/Tokyo',
    openTime: {
      hours: 9,
      minutes: 0,
    },
    closeTime: {
      hours: 15,
      minutes: 0,
    },
  },
  {
    id: 'hkex',
    city: 'Hong Kong',
    country: 'Hong Kong',
    flag: 'hk',
    name: 'Hong Kong Stock Exchange',
    timeZone: 'Hongkong',
    openTime: {
      hours: 9,
      minutes: 30,
    },
    closeTime: {
      hours: 16,
      minutes: 0,
    },
  },
  {
    id: 'sse',
    city: 'Shanghai',
    country: 'China',
    flag: 'cn',
    name: 'Shanghai Stock Exchange',
    timeZone: 'Asia/Shanghai',
    openTime: {
      hours: 9,
      minutes: 30,
    },
    closeTime: {
      hours: 16,
      minutes: 0,
    },
  },
  {
    id: 'sgx',
    city: 'Singapore',
    country: 'Singapore',
    flag: 'sg',
    name: 'Singapore Exchange',
    timeZone: 'Asia/Singapore',
    openTime: {
      hours: 9,
      minutes: 0,
    },
    closeTime: {
      hours: 17,
      minutes: 0,
    },
  },
  {
    id: 'nse',
    city: 'Mumbai',
    country: 'India',
    flag: 'in',
    name: 'India National Stock Exchange',
    timeZone: 'Asia/Calcutta',
    openTime: {
      hours: 9,
      minutes: 15,
    },
    closeTime: {
      hours: 15,
      minutes: 30,
    },
  },
  {
    id: 'rusx',
    city: 'Moscow',
    country: 'Russia',
    flag: 'ru',
    name: 'OTC Russia',
    timeZone: 'Europe/Moscow',
    openTime: {
      hours: 10,
      minutes: 0,
    },
    closeTime: {
      hours: 17,
      minutes: 0,
    },
  },
  {
    id: 'xist',
    city: 'Istanbul',
    country: 'Turkey',
    flag: 'tr',
    name: 'Istanbul Stock Exchange',
    timeZone: 'Europe/Istanbul',
    openTime: {
      hours: 10,
      minutes: 0,
    },
    closeTime: {
      hours: 18,
      minutes: 0,
    },
  },
  {
    id: 'eurex',
    city: 'Berlin',
    country: 'Germany',
    flag: 'de',
    name: 'Eurex Germany',
    timeZone: 'Europe/Berlin',
    openTime: {
      hours: 8,
      minutes: 55,
    },
    closeTime: {
      hours: 17,
      minutes: 45,
    },
  },
  {
    id: 'xpar',
    city: 'Paris',
    country: 'France',
    flag: 'fr',
    name: 'Euronext Paris Exchange',
    timeZone: 'Europe/Paris',
    openTime: {
      hours: 9,
      minutes: 0,
    },
    closeTime: {
      hours: 17,
      minutes: 30,
    },
  },
  {
    id: 'lse',
    city: 'London',
    country: 'GB',
    flag: 'gb',
    name: 'London Stock Exchange',
    timeZone: 'Europe/London',
    openTime: {
      hours: 8,
      minutes: 0,
    },
    closeTime: {
      hours: 16,
      minutes: 30,
    },
  },
  {
    id: 'xdub',
    city: 'Dublin',
    country: 'Ireland',
    flag: 'ie',
    name: 'Irish Stock Exchange',
    timeZone: 'Europe/Dublin',
    openTime: {
      hours: 9,
      minutes: 0,
    },
    closeTime: {
      hours: 17,
      minutes: 30,
    },
  },
  {
    id: 'nyse',
    city: 'New York',
    country: 'USA',
    flag: 'us',
    name: 'New York Stock Exchange',
    timeZone: 'America/New_York',
    openTime: {
      hours: 9,
      minutes: 30,
    },
    closeTime: {
      hours: 16,
      minutes: 0,
    },
  },
];
